name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - "apps/gateway/**"

jobs:
  just-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Check out code
        run: echo "app gateway was changed"

  # test-ci:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [18.x, 20.x]

  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "yarn"

  #     - name: Install dependencies
  #       run: yarn install --immutable --immutable-cache --check-cache

  #     - name: Build
  #       run: yarn build

  #     - name: Test
  #       run: yarn test

  # deploy-test:
  #   needs: test-ci
  #   if: github.ref == 'refs/heads/develop'
  #   runs-on: ubuntu-latest
  #   concurrency: deploy-to-test
  #   environment: test
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: Use Node.js 18.x
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 18.x
  #     - run: docker build -f -t setup-nodejs .
  #     - run: echo "Deploy"

  # deploy-production:
  #   needs: test-ci
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-20.04
  #   concurrency: deploy-to-production
  #   environment: production
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js 10.x
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16.x
  #     - run: docker build -t setup-nodejs .
  #     - run: echo "Deploy"
